import { NextRequest,NextResponse } from 'next/server'
import { timingSafeEqual } from 'node:crypto'
import { createAdminClient } from '@/lib/supabase/server'
import { sendEmail } from '@/lib/email/brevo'
export const runtime='nodejs'
function authorized(request:NextRequest){const expected=process.env.INTERVIEW_WORKER_SECRET||process.env.CRON_SECRET;const received=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'')??'';if(!expected||received.length!==expected.length)return false;return timingSafeEqual(Buffer.from(received),Buffer.from(expected))}
const esc=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
export async function GET(request:NextRequest){return POST(request)}
export async function POST(request:NextRequest){if(!authorized(request))return NextResponse.json({message:'Unauthorized.'},{status:401});const db=createAdminClient();await db.rpc('interview_expire_proposals');const {data:jobs,error}=await db.rpc('interview_outbox_claim',{p_limit:30});if(error)return NextResponse.json({message:'Could not claim interview notifications.'},{status:503});let sent=0,failed=0
 for(const job of jobs??[]){try{if(job.payload?.action==='reminder'){const {data:booking}=await db.from('interview_bookings').select('id,state,revision,starts_at').eq('id',job.payload.bookingId).maybeSingle();if(!booking||booking.state!=='confirmed'||booking.revision!==job.payload.revision||new Date(booking.starts_at)<=new Date()){await db.from('interview_notification_outbox').update({state:'cancelled',lease_until:null}).eq('id',job.id);continue}}
 if(job.channel==='dashboard'){if(job.recipient_user_id){await db.from('user_notifications').upsert({user_id:job.recipient_user_id,title:job.payload.title??'Interview update',body:job.payload.body??'',category:job.payload.category??'interview',cta_label:job.payload.cta_label??'View interview',cta_url:job.payload.cta_url??'/dashboard/me/interview',delivered_at:new Date().toISOString(),metadata:{outboxId:job.id},interview_outbox_id:job.id},{onConflict:'interview_outbox_id',ignoreDuplicates:true})}}
 else {const recipient=job.recipient_email||process.env.INTERVIEW_ADMIN_EMAIL||process.env.ADMIN_NOTIFICATION_EMAIL;if(!recipient)throw new Error('Set INTERVIEW_ADMIN_EMAIL or ADMIN_NOTIFICATION_EMAIL.');const subject=String(job.payload.title??'Top100 interview update');const body=String(job.payload.body??'There is an update to an interview request.');const html=`<div style="font-family:Arial,sans-serif;color:#171717;max-width:600px"><h2>${esc(subject)}</h2><p>${esc(body)}</p><p><a href="${esc(new URL(String(job.payload.cta_url??'/admin/interviews'),process.env.NEXT_PUBLIC_SITE_URL||'https://www.top100afl.com').toString())}">Open interview bookings</a></p></div>`;if(!await sendEmail({to:recipient,subject,html,text:`${body}\n\n${String(job.payload.cta_url??'/admin/interviews')}`}))throw new Error('Brevo did not confirm delivery.')}
 await db.from('interview_notification_outbox').update({state:'sent',sent_at:new Date().toISOString(),lease_until:null,last_error:null}).eq('id',job.id);sent++
 }catch(error){const attempts=Number(job.attempts??1);await db.from('interview_notification_outbox').update({state:attempts>=8?'failed':'pending',due_at:new Date(Date.now()+Math.min(360,2**attempts)*60_000).toISOString(),lease_until:null,last_error:error instanceof Error?error.message:'Delivery failed.'}).eq('id',job.id);failed++}}
 return NextResponse.json({claimed:(jobs??[]).length,sent,failed})}
