-- =====================================================================
-- SETUP-ALL.sql — generated by scripts/build-setup-sql.mjs. DO NOT EDIT.
-- Regenerate with:  node scripts/build-setup-sql.mjs
--
-- Paste the whole file into the Supabase SQL editor and run it once. It is
-- idempotent: running it again is a no-op, so it is safe to re-run after
-- adding a migration.
--
-- Order matters. supabase/SETUP-MEMBER-HUB.sql must come first because it adds
-- profiles.membership_status and the member-hub tables that every later file
-- references.
-- =====================================================================

------------------------------------------------------------------------
-- BEGIN supabase/SETUP-MEMBER-HUB.sql
------------------------------------------------------------------------
-- =====================================================================
-- ONE-TIME SETUP: member hub database objects  (safe to re-run)
-- =====================================================================
-- The live database is missing everything the member dashboard needs:
--   * profiles membership columns  -> everyone shows "pending" forever and
--     the admin Approve button errors
--   * access_codes                 -> invite-code signup always fails
--   * user_notifications           -> admin broadcasts have nowhere to go
--   * member_features              -> "get featured" submissions fail
--   * dm_conversations/dm_messages -> the new Messages section
--
-- HOW TO RUN: Supabase Dashboard -> SQL Editor -> paste this whole file
-- -> Run. Every statement is idempotent, so re-running is harmless.
--
-- This file consolidates, in order:
--   1. user_notifications               (from supabase/schema.sql)
--   2. 20260706_access_codes_and_membership.sql
--   3. 20260716_direct_messages.sql
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. USER NOTIFICATIONS (in-app dashboard notifications)
-- ---------------------------------------------------------------------
create table if not exists public.user_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  title text not null,
  body text,
  category text default 'general',
  cta_label text,
  cta_url text,
  scheduled_for timestamp with time zone,
  delivered_at timestamp with time zone default now(),
  read_at timestamp with time zone,
  metadata jsonb default '{}'::jsonb
);

create index if not exists user_notifications_user_idx on public.user_notifications(user_id);
create index if not exists user_notifications_category_idx on public.user_notifications(category);

alter table public.user_notifications enable row level security;

DO $$ BEGIN
  create policy "Users read their notifications" on public.user_notifications
    for select using (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  create policy "Users update notification status" on public.user_notifications
    for update using (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  create policy "Service inserts notifications" on public.user_notifications
    for insert with check (auth.role() = 'service_role');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------
-- 2a. ACCESS CODES — admin issues these; users redeem one at signup.
-- ---------------------------------------------------------------------
create table if not exists public.access_codes (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique,
  label       text default 'Awardee invite',
  status      text not null default 'active'
              check (status in ('active', 'used', 'expired', 'revoked')),
  uses_left   integer not null default 1,
  email       text,
  created_by  uuid,
  used_by     uuid,
  used_at     timestamptz,
  expires_at  timestamptz not null default (now() + interval '90 days'),
  created_at  timestamptz not null default now()
);

create index if not exists access_codes_code_idx   on public.access_codes (code);
create index if not exists access_codes_status_idx  on public.access_codes (status);
create index if not exists access_codes_created_idx on public.access_codes (created_at desc);

alter table public.access_codes enable row level security;

DO $$ BEGIN
  create policy "Service role manages access codes" on public.access_codes
    for all to service_role using (true) with check (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------
-- 2b. PROFILES — membership status, BIO limits, notification prefs.
-- ---------------------------------------------------------------------
alter table public.profiles
  add column if not exists membership_status text not null default 'pending';

DO $$ BEGIN
  alter table public.profiles
    add constraint profiles_membership_status_check
    check (membership_status in ('pending', 'approved', 'rejected', 'suspended'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Legacy drift fix: the live database has a NOT NULL "Email" (capital E)
-- column from an old import that the app never writes, so every new profile
-- insert — including real signups — fails. Make it optional.
DO $$ BEGIN
  alter table public.profiles alter column "Email" drop not null;
EXCEPTION WHEN undefined_column THEN NULL; END $$;

alter table public.profiles add column if not exists bio_update_count  integer not null default 0;
alter table public.profiles add column if not exists bio_update_limit  integer not null default 2;
alter table public.profiles add column if not exists notification_prefs jsonb   not null default '{}'::jsonb;
alter table public.profiles add column if not exists organization text;
alter table public.profiles add column if not exists field text;
alter table public.profiles add column if not exists access_code text;

create index if not exists profiles_membership_status_idx on public.profiles (membership_status);

-- ---------------------------------------------------------------------
-- 2c. MEMBER FEATURES — "feature my story" submissions.
-- ---------------------------------------------------------------------
create table if not exists public.member_features (
  id            uuid primary key default gen_random_uuid(),
  member_id     uuid not null references public.profiles (id) on delete cascade,
  member_name   text not null,
  title         text not null,
  category      text not null default 'bio'
                check (category in ('bio', 'story', 'product', 'project')),
  summary       text,
  contact_email text,
  status        text not null default 'pending'
                check (status in ('pending', 'reviewing', 'approved', 'published')),
  created_at    timestamptz not null default now()
);

create index if not exists member_features_member_idx on public.member_features (member_id);
create index if not exists member_features_status_idx on public.member_features (status);
create index if not exists member_features_created_idx on public.member_features (created_at desc);

alter table public.member_features enable row level security;

DO $$ BEGIN
  create policy "Service role manages member features" on public.member_features
    for all to service_role using (true) with check (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  create policy "Members read their own features" on public.member_features
    for select to authenticated using (auth.uid() = member_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  create policy "Members create their own features" on public.member_features
    for insert to authenticated with check (auth.uid() = member_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------
-- 2d. PROFILES privilege guard — stops members self-approving or
--     self-promoting through PostgREST (RLS cannot restrict columns).
-- ---------------------------------------------------------------------
create or replace function public.profiles_guard_privileged_columns()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if auth.role() = 'service_role' then
    return new;
  end if;

  new.role              := old.role;
  new.membership_status := old.membership_status;
  new.bio_update_count  := old.bio_update_count;
  new.bio_update_limit  := old.bio_update_limit;
  new.access_code       := old.access_code;

  return new;
end;
$$;

drop trigger if exists profiles_guard_privileged_columns on public.profiles;
create trigger profiles_guard_privileged_columns
  before update on public.profiles
  for each row execute function public.profiles_guard_privileged_columns();

-- ---------------------------------------------------------------------
-- 3a. DIRECT MESSAGE CONVERSATIONS — one row per member pair.
-- ---------------------------------------------------------------------
create table if not exists public.dm_conversations (
  id               uuid primary key default gen_random_uuid(),
  member_one       uuid not null references public.profiles (id) on delete cascade,
  member_two       uuid not null references public.profiles (id) on delete cascade,
  created_at       timestamptz not null default now(),
  last_message_at  timestamptz not null default now(),
  constraint dm_conversations_distinct_members check (member_one <> member_two),
  constraint dm_conversations_ordered_pair check (member_one < member_two),
  constraint dm_conversations_unique_pair unique (member_one, member_two)
);

create index if not exists dm_conversations_member_one_idx on public.dm_conversations (member_one, last_message_at desc);
create index if not exists dm_conversations_member_two_idx on public.dm_conversations (member_two, last_message_at desc);

alter table public.dm_conversations enable row level security;

DO $$ BEGIN
  create policy "Service role manages dm conversations" on public.dm_conversations
    for all to service_role using (true) with check (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------
-- 3b. DIRECT MESSAGES
-- ---------------------------------------------------------------------
create table if not exists public.dm_messages (
  id               uuid primary key default gen_random_uuid(),
  conversation_id  uuid not null references public.dm_conversations (id) on delete cascade,
  sender_id        uuid not null references public.profiles (id) on delete cascade,
  body             text not null check (char_length(body) between 1 and 4000),
  created_at       timestamptz not null default now(),
  read_at          timestamptz
);

create index if not exists dm_messages_conversation_idx on public.dm_messages (conversation_id, created_at);
create index if not exists dm_messages_unread_idx on public.dm_messages (conversation_id, sender_id) where read_at is null;

alter table public.dm_messages enable row level security;

DO $$ BEGIN
  create policy "Service role manages dm messages" on public.dm_messages
    for all to service_role using (true) with check (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------
-- 3c. TIGHTEN public.messages (contact/application inbox) RLS.
--     The old policies let ANY authenticated user read/update every
--     submission. Restrict to admins; keep public inserts.
-- ---------------------------------------------------------------------
drop policy if exists "Authenticated users can read messages" on public.messages;
drop policy if exists "Authenticated users can update messages" on public.messages;

DO $$ BEGIN
  create policy "Admins can view messages" on public.messages
    for select to authenticated using (
      exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.role in ('admin', 'superadmin')
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  create policy "Admins can update messages" on public.messages
    for update to authenticated using (
      exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.role in ('admin', 'superadmin')
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  create policy "Admins can delete messages" on public.messages
    for delete to authenticated using (
      exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.role in ('admin', 'superadmin')
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------
-- Comments
-- ---------------------------------------------------------------------
comment on table  public.access_codes is 'Admin-issued signup access codes. Redeemed once (or uses_left times) at signup.';
comment on column public.profiles.membership_status is 'pending | approved | rejected | suspended — admin-controlled membership state.';
comment on table  public.member_features is 'Member-hub "feature my story" submissions, reviewed by admins.';
comment on table  public.dm_conversations is 'Member-to-member direct message threads (dashboard Messages section).';
comment on table  public.dm_messages is 'Messages inside dm_conversations. Written via service-role API only.';

------------------------------------------------------------------------
-- END supabase/SETUP-MEMBER-HUB.sql
------------------------------------------------------------------------

------------------------------------------------------------------------
-- BEGIN supabase/migrations/20260104_create_feature_requests.sql
------------------------------------------------------------------------
-- Create feature_requests table for news feature requests
CREATE TABLE IF NOT EXISTS feature_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    awardee_id UUID REFERENCES awardees(id) ON DELETE SET NULL,
    awardee_name TEXT NOT NULL,
    has_own_article BOOLEAN DEFAULT false,
    article_content TEXT,
    needs_article_written BOOLEAN DEFAULT false,
    contact_email TEXT NOT NULL,
    whatsapp_number TEXT NOT NULL,
    amount DECIMAL(10, 2) DEFAULT 40000,
    currency TEXT DEFAULT 'NGN',
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'contacted', 'paid', 'in_progress', 'published', 'cancelled')),
    payment_status TEXT CHECK (payment_status IN ('pending', 'confirmed', 'refunded')),
    admin_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add indexes for common queries
CREATE INDEX IF NOT EXISTS idx_feature_requests_awardee_id ON feature_requests(awardee_id);
CREATE INDEX IF NOT EXISTS idx_feature_requests_status ON feature_requests(status);
CREATE INDEX IF NOT EXISTS idx_feature_requests_created_at ON feature_requests(created_at DESC);

-- Add RLS policies
ALTER TABLE feature_requests ENABLE ROW LEVEL SECURITY;

-- Policies are dropped first so this file can be re-run. Without this it is the
-- only migration in the tree that fails on a second execution (42710,
-- "policy already exists"), which would abort supabase/SETUP-ALL.sql partway
-- through and leave the database half-migrated.

-- Allow service role full access
DROP POLICY IF EXISTS "Service role has full access to feature_requests" ON feature_requests;
CREATE POLICY "Service role has full access to feature_requests" ON feature_requests
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Allow authenticated admins to read
DROP POLICY IF EXISTS "Admins can view feature_requests" ON feature_requests;
CREATE POLICY "Admins can view feature_requests" ON feature_requests
    FOR SELECT
    TO authenticated
    USING (true);

-- Allow public insert (for awardees to submit requests)
DROP POLICY IF EXISTS "Anyone can submit feature_requests" ON feature_requests;
CREATE POLICY "Anyone can submit feature_requests" ON feature_requests
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

-- Add comment for documentation
COMMENT ON TABLE feature_requests IS 'Stores news feature requests from awardees who want to be featured in local and international news channels';

------------------------------------------------------------------------
-- END supabase/migrations/20260104_create_feature_requests.sql
------------------------------------------------------------------------

------------------------------------------------------------------------
-- BEGIN supabase/migrations/20260726_award_orders.sql
------------------------------------------------------------------------
-- Award orders: one physical Africa Future Leaders award per member.
-- Prerequisite: supabase/SETUP-MEMBER-HUB.sql must already have been run.
create extension if not exists "pgcrypto";

create table if not exists public.award_orders (
  id uuid primary key default gen_random_uuid(),
  -- restrict, not cascade: payment history (paystack_reference, paid_at,
  -- gig_waybill) must survive, so a profile cannot be deleted while it still
  -- has an award order. The order must be dealt with first.
  profile_id uuid not null references public.profiles(id) on delete restrict,
  awardee_id uuid,
  cohort_year integer,

  status text not null default 'draft' check (status in (
    'draft','quoted','quote_failed','awaiting_payment',
    'paid','dispatched','in_transit','delivered','cancelled'
  )),

  recipient_name text,
  phone text,
  email text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  country text,
  postal_code text,

  -- Every amount is integer kobo. 2000000 = NGN 20,000.
  award_amount_kobo integer not null default 2000000 check (award_amount_kobo >= 0),
  shipping_amount_kobo integer check (shipping_amount_kobo >= 0),
  total_amount_kobo integer check (total_amount_kobo >= 0),
  currency text not null default 'NGN',

  gig_quote jsonb,
  gig_quote_expires_at timestamptz,
  gig_waybill text,
  gig_tracking_url text,
  gig_last_status text,
  gig_response jsonb,

  paystack_reference text unique,
  paystack_status text,
  paid_at timestamptz,

  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- A total is required once the order has reached checkout: without this,
  -- `total_amount_kobo >= 0` alone would still pass with a NULL total, and a
  -- row could reach `paid` with no recorded amount.
  constraint award_orders_total_required_when_charging check (
    status not in ('awaiting_payment', 'paid', 'dispatched', 'in_transit', 'delivered')
    or total_amount_kobo is not null
  ),

  -- The total must equal award + shipping whenever it is set. Both NULL is the
  -- draft/quote_failed state and is allowed; exactly one NULL is inconsistent
  -- and must be rejected. IS NULL/IS NOT NULL keeps that case FALSE rather
  -- than NULL, since a CHECK constraint otherwise passes on a NULL result.
  constraint award_orders_total_is_award_plus_shipping check (
    (shipping_amount_kobo is null and total_amount_kobo is null)
    or (
      shipping_amount_kobo is not null
      and total_amount_kobo is not null
      and total_amount_kobo = award_amount_kobo + shipping_amount_kobo
    )
  )
);

-- One live award per member. Cancelled orders do not block a fresh attempt.
create unique index if not exists award_orders_one_active_per_profile
  on public.award_orders (profile_id)
  where status <> 'cancelled';

create index if not exists award_orders_status_idx on public.award_orders (status);
create index if not exists award_orders_reference_idx on public.award_orders (paystack_reference);

create or replace function public.touch_award_orders_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists award_orders_set_updated_at on public.award_orders;
create trigger award_orders_set_updated_at
  before update on public.award_orders
  for each row execute function public.touch_award_orders_updated_at();

alter table public.award_orders enable row level security;

do $$ begin
  create policy "Members read their own award order" on public.award_orders
    for select using (auth.uid() = profile_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Service role manages award orders" on public.award_orders
    for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
exception when duplicate_object then null; end $$;

------------------------------------------------------------------------
-- END supabase/migrations/20260726_award_orders.sql
------------------------------------------------------------------------

------------------------------------------------------------------------
-- BEGIN supabase/migrations/20260727_interviews.sql
------------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- IMPACT INTERVIEWS
-- Awardee video/written interview series + the application queue that feeds it.
-- ---------------------------------------------------------------------------

-- Applications first: interviews.application_id references this table.
create table if not exists public.interview_applications (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text not null,
  phone text,
  country text,
  cohort_year integer,
  role_title text,
  organisation text,
  bio text not null,
  impact_story text not null,
  linkedin_url text,
  other_link text,
  preferred_format text not null default 'either'
    check (preferred_format in ('video', 'written', 'either')),
  headshot_path text,
  matched_awardee_id uuid references public.awardees(id) on delete set null,
  verification text not null default 'unmatched'
    check (verification in ('matched', 'unmatched')),
  status text not null default 'pending'
    check (status in ('pending', 'shortlisted', 'scheduled', 'published', 'declined')),
  admin_notes text,
  scheduled_at timestamptz,
  published_interview_id uuid,
  consent_recorded boolean not null default false,
  consent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists interview_applications_status_idx
  on public.interview_applications (status, created_at desc);
create index if not exists interview_applications_email_idx
  on public.interview_applications (lower(email));
create index if not exists interview_applications_matched_idx
  on public.interview_applications (matched_awardee_id);

create table if not exists public.interviews (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  format text not null default 'video' check (format in ('video', 'written')),
  video_id text,
  duration_seconds integer,
  thumbnail_url text,
  pull_quote text,
  summary text,
  body text,
  awardee_id uuid references public.awardees(id) on delete set null,
  awardee_name text not null,
  country text,
  cohort_year integer,
  topics text[] not null default '{}',
  featured boolean not null default false,
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_at timestamptz,
  sort_order integer not null default 0,
  application_id uuid references public.interview_applications(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- A video interview without a video id would render an empty player.
  constraint interviews_video_requires_id
    check (format <> 'video' or (video_id is not null and length(video_id) > 0))
);

create index if not exists interviews_slug_idx on public.interviews (slug);
create index if not exists interviews_status_published_idx
  on public.interviews (status, published_at desc);
create index if not exists interviews_featured_idx on public.interviews (featured);
create index if not exists interviews_awardee_idx on public.interviews (awardee_id);
create index if not exists interviews_cohort_idx on public.interviews (cohort_year);

-- Reverse link, added now that public.interviews exists.
DO $$ BEGIN
  alter table public.interview_applications
    add constraint interview_applications_published_interview_fkey
    foreign key (published_interview_id)
    references public.interviews(id) on delete set null;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- updated_at triggers, matching public.handle_awardee_updated.
create or replace function public.handle_interview_updated()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_interview_updated on public.interviews;
create trigger on_interview_updated
  before update on public.interviews
  for each row execute function public.handle_interview_updated();

drop trigger if exists on_interview_application_updated on public.interview_applications;
create trigger on_interview_application_updated
  before update on public.interview_applications
  for each row execute function public.handle_interview_updated();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.interviews enable row level security;
alter table public.interview_applications enable row level security;

DO $$ BEGIN
  create policy "Published interviews are public" on public.interviews
    for select using (status = 'published');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  create policy "Service manages interviews" on public.interviews
    for all using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Applications carry personal data: service role only, no public policy at all.
DO $$ BEGIN
  create policy "Service manages interview applications" on public.interview_applications
    for all using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------------
-- PRIVATE STORAGE BUCKET for applicant headshots
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('interview-applications', 'interview-applications', false)
on conflict (id) do nothing;

------------------------------------------------------------------------
-- END supabase/migrations/20260727_interviews.sql
------------------------------------------------------------------------

------------------------------------------------------------------------
-- BEGIN supabase/migrations/20260728_award_notification_log.sql
------------------------------------------------------------------------
-- Award notification log: one row per (order, milestone), claimed BEFORE the
-- email/in-app notice is sent. The unique (order_id, status) constraint is the
-- exactly-once mechanism — Paystack retries the same webhook, and without it
-- the member gets "payment confirmed" over and over.
--
-- Prerequisite: supabase/migrations/20260726_award_orders.sql must already
-- have been run.
create extension if not exists "pgcrypto";

create table if not exists public.award_notification_log (
  id uuid primary key default gen_random_uuid(),
  -- cascade: the log is a delivery trail for an order, worthless without it.
  order_id uuid not null references public.award_orders(id) on delete cascade,
  -- Nullable and unconstrained by design: the log must survive even if the
  -- profile is later removed, and it is only ever read by admins.
  profile_id uuid,
  status text not null check (status in ('paid','dispatched','in_transit','delivered')),
  -- Which channels actually went out: 'in_app', 'email'.
  channels text[] not null default '{}',
  sent_at timestamptz,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- The exactly-once guarantee.
  constraint award_notification_log_once_per_status unique (order_id, status)
);

create index if not exists award_notification_log_order_idx
  on public.award_notification_log (order_id);
create index if not exists award_notification_log_profile_idx
  on public.award_notification_log (profile_id);
-- Rows that were claimed but never sent are the operational queue to inspect.
create index if not exists award_notification_log_unsent_idx
  on public.award_notification_log (created_at)
  where sent_at is null;

create or replace function public.touch_award_notification_log_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists award_notification_log_set_updated_at on public.award_notification_log;
create trigger award_notification_log_set_updated_at
  before update on public.award_notification_log
  for each row execute function public.touch_award_notification_log_updated_at();

alter table public.award_notification_log enable row level security;

-- Admin-only select. Members see their milestones through user_notifications
-- and email; this table is the operational trail behind /admin/awards.
drop policy if exists "Admins read the award notification log" on public.award_notification_log;
create policy "Admins read the award notification log" on public.award_notification_log
  for select using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- Server routes use the service-role client and bypass RLS; this is defence in
-- depth so no anon/authenticated key can ever write here.
drop policy if exists "Service role manages the award notification log" on public.award_notification_log;
create policy "Service role manages the award notification log" on public.award_notification_log
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

------------------------------------------------------------------------
-- END supabase/migrations/20260728_award_notification_log.sql
------------------------------------------------------------------------

------------------------------------------------------------------------
-- BEGIN supabase/migrations/20260728_event_invitations.sql
------------------------------------------------------------------------
-- Event invitations + RSVP for awardees.
--
-- The FK points at public.events (supabase/migrations/005_create_events_table.sql),
-- which is the table the live /api/events route and lib/homepage-feed.ts both read
-- (`supabase.from('events')`). public.upcoming_events (003) is legacy and unread.
--
-- Prerequisite: supabase/SETUP-MEMBER-HUB.sql must already have been run
-- (profiles.membership_status is used to resolve the 'approved' audience).
create extension if not exists "pgcrypto";

create table if not exists public.event_invitations (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null
    constraint event_invitations_event_id_fkey references public.events(id) on delete cascade,
  -- The constraint is named explicitly because the table has two FKs to
  -- profiles: PostgREST cannot embed the member without an unambiguous hint,
  -- and the admin roster query uses this name.
  profile_id uuid not null
    constraint event_invitations_profile_id_fkey references public.profiles(id) on delete cascade,
  -- The admin who sent it. Kept as a soft link: if that admin's profile is
  -- deleted the invitation itself must survive, so it is nulled, not cascaded.
  invited_by uuid
    constraint event_invitations_invited_by_fkey references public.profiles(id) on delete set null,
  -- Optional personal note from the admin, shown on the member's card.
  message text,
  rsvp text not null default 'pending'
       check (rsvp in ('pending', 'attending', 'declined', 'maybe')),
  rsvp_at timestamptz,
  seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Re-inviting the same member to the same event is an update (in practice a
  -- no-op, since the admin route inserts with ON CONFLICT DO NOTHING), never a
  -- second row that would reset an RSVP they already gave.
  constraint event_invitations_unique_per_member unique (event_id, profile_id)
);

-- Drives both the member's "your invitations" list and the nav pending badge.
create index if not exists event_invitations_profile_rsvp_idx
  on public.event_invitations (profile_id, rsvp);

-- Drives the admin RSVP roster for one event.
create index if not exists event_invitations_event_idx
  on public.event_invitations (event_id);

create or replace function public.touch_event_invitations_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists event_invitations_set_updated_at on public.event_invitations;
create trigger event_invitations_set_updated_at
  before update on public.event_invitations
  for each row execute function public.touch_event_invitations_updated_at();

-- A member may only ever move rsvp / rsvp_at / seen_at. Pin every other column
-- back to its previous value for non-service-role callers, so a direct
-- PostgREST update cannot re-point an invitation at another event or member,
-- or forge who sent it. RLS alone cannot express "only these columns".
create or replace function public.event_invitations_guard_columns()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() = 'service_role' then
    return new;
  end if;

  new.id         := old.id;
  new.event_id   := old.event_id;
  new.profile_id := old.profile_id;
  new.invited_by := old.invited_by;
  new.message    := old.message;
  new.created_at := old.created_at;

  return new;
end;
$$;

drop trigger if exists event_invitations_guard_columns_trg on public.event_invitations;
create trigger event_invitations_guard_columns_trg
  before update on public.event_invitations
  for each row execute function public.event_invitations_guard_columns();

alter table public.event_invitations enable row level security;

drop policy if exists "Members read their own event invitations" on public.event_invitations;
create policy "Members read their own event invitations" on public.event_invitations
  for select using (auth.uid() = profile_id);

-- The USING clause scopes the update to their own row; the WITH CHECK clause
-- stops them handing the row to someone else. The column guard trigger above
-- restricts *which* columns the update may actually move.
drop policy if exists "Members rsvp to their own event invitations" on public.event_invitations;
create policy "Members rsvp to their own event invitations" on public.event_invitations
  for update using (auth.uid() = profile_id) with check (auth.uid() = profile_id);

drop policy if exists "Service role manages event invitations" on public.event_invitations;
create policy "Service role manages event invitations" on public.event_invitations
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

comment on table public.event_invitations is
  'Targeted invitations to public.events rows, with the member RSVP. One row per (event, member).';
comment on column public.event_invitations.rsvp is
  'pending | attending | declined | maybe — pending means invited but not yet answered.';
comment on column public.event_invitations.seen_at is
  'Stamped the first time the member''s dashboard renders the invitation; drives the "New invitation" pill.';

------------------------------------------------------------------------
-- END supabase/migrations/20260728_event_invitations.sql
------------------------------------------------------------------------

------------------------------------------------------------------------
-- BEGIN supabase/migrations/20260728_member_groups.sql
------------------------------------------------------------------------
-- Awardee groups: topic communities awardees join and talk inside.
-- Prerequisite: supabase/SETUP-MEMBER-HUB.sql must already have been run
-- (this file references public.profiles).
--
-- Idempotent: safe to run more than once.
create extension if not exists "pgcrypto";

-- The RLS policies below gate writes on profiles.membership_status, and the
-- live database may not have had SETUP-MEMBER-HUB.sql applied yet. This is the
-- exact same guarded statement that file uses, so running either order works.
alter table public.profiles
  add column if not exists membership_status text not null default 'pending';

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.member_groups (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text,
  topic text,
  cover_url text,

  -- open    — any approved member joins instantly
  -- request — joining creates a `pending` membership an admin/owner approves
  -- private — invitation only; never listed to non-members
  visibility text not null default 'open' check (visibility in ('open', 'request', 'private')),

  created_by uuid references public.profiles(id) on delete set null,
  is_archived boolean not null default false,

  -- Maintained by the member_group_members trigger below. Never write it by
  -- hand: the trigger recomputes it from scratch on every membership change.
  member_count integer not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.member_group_members (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.member_groups(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('member', 'moderator', 'owner')),
  status text not null default 'active' check (status in ('pending', 'active', 'banned')),
  joined_at timestamptz not null default now(),
  -- Drives the unread badge: messages newer than this are unread.
  last_read_at timestamptz,
  unique (group_id, profile_id)
);

create table if not exists public.member_group_messages (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.member_groups(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000),
  -- Messages are only ever soft-deleted, so moderation stays auditable.
  is_deleted boolean not null default false,
  deleted_by uuid,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

create index if not exists member_groups_visibility_idx
  on public.member_groups (visibility) where is_archived = false;
create index if not exists member_group_members_profile_idx
  on public.member_group_members (profile_id);
create index if not exists member_group_members_group_status_idx
  on public.member_group_members (group_id, status);
create index if not exists member_group_messages_group_created_idx
  on public.member_group_messages (group_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

create or replace function public.touch_member_groups_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists member_groups_set_updated_at on public.member_groups;
create trigger member_groups_set_updated_at
  before update on public.member_groups
  for each row execute function public.touch_member_groups_updated_at();

-- Recompute member_count from the actual rows rather than incrementing a
-- counter: an increment drifts the moment two membership changes interleave,
-- a full recount inside the same transaction cannot.
create or replace function public.sync_member_group_member_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_group uuid;
begin
  if tg_op = 'DELETE' then
    target_group := old.group_id;
  else
    target_group := new.group_id;
  end if;

  update public.member_groups g
     set member_count = (
       select count(*)
         from public.member_group_members m
        where m.group_id = target_group
          and m.status = 'active'
     )
   where g.id = target_group;

  -- A membership row moved between groups: the old group needs recounting too.
  if tg_op = 'UPDATE' and old.group_id is distinct from new.group_id then
    update public.member_groups g
       set member_count = (
         select count(*)
           from public.member_group_members m
          where m.group_id = old.group_id
            and m.status = 'active'
       )
     where g.id = old.group_id;
  end if;

  return null;
end;
$$;

drop trigger if exists member_group_members_sync_count on public.member_group_members;
create trigger member_group_members_sync_count
  after insert or update or delete on public.member_group_members
  for each row execute function public.sync_member_group_member_count();

-- ---------------------------------------------------------------------------
-- Policy helpers
--
-- These are `security definer` so the policies below can read
-- member_group_members without re-entering that table's own RLS policies,
-- which would recurse infinitely.
-- ---------------------------------------------------------------------------

create or replace function public.is_site_admin(pid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
     where p.id = pid and p.role in ('admin', 'superadmin')
  );
$$;

-- Reading rights: active members and members still awaiting approval.
create or replace function public.is_group_participant(gid uuid, pid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.member_group_members m
     where m.group_id = gid and m.profile_id = pid
       and m.status in ('active', 'pending')
  );
$$;

-- Writing rights: an approved, active membership only.
create or replace function public.is_active_group_member(gid uuid, pid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.member_group_members m
     where m.group_id = gid and m.profile_id = pid and m.status = 'active'
  );
$$;

create or replace function public.is_group_admin(gid uuid, pid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.member_group_members m
     where m.group_id = gid and m.profile_id = pid
       and m.status = 'active' and m.role in ('owner', 'moderator')
  );
$$;

-- ---------------------------------------------------------------------------
-- RLS
--
-- The API routes use the service-role client and bypass all of this; these
-- policies are defence in depth for anything that reaches the tables with a
-- member's own JWT.
-- ---------------------------------------------------------------------------

alter table public.member_groups enable row level security;
alter table public.member_group_members enable row level security;
alter table public.member_group_messages enable row level security;

-- member_groups -------------------------------------------------------------

drop policy if exists "Service role manages member groups" on public.member_groups;
create policy "Service role manages member groups" on public.member_groups
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

drop policy if exists "Members read listed and joined groups" on public.member_groups;
create policy "Members read listed and joined groups" on public.member_groups
  for select using (
    visibility <> 'private'
    or public.is_group_participant(id, auth.uid())
    or public.is_site_admin(auth.uid())
  );

drop policy if exists "Approved members create groups" on public.member_groups;
create policy "Approved members create groups" on public.member_groups
  for insert with check (
    created_by = auth.uid()
    and exists (
      select 1 from public.profiles p
       where p.id = auth.uid() and p.membership_status = 'approved'
    )
  );

drop policy if exists "Group admins update their group" on public.member_groups;
create policy "Group admins update their group" on public.member_groups
  for update using (
    public.is_group_admin(id, auth.uid()) or public.is_site_admin(auth.uid())
  ) with check (
    public.is_group_admin(id, auth.uid()) or public.is_site_admin(auth.uid())
  );

drop policy if exists "Site admins delete groups" on public.member_groups;
create policy "Site admins delete groups" on public.member_groups
  for delete using (public.is_site_admin(auth.uid()));

-- member_group_members ------------------------------------------------------

drop policy if exists "Service role manages group memberships" on public.member_group_members;
create policy "Service role manages group memberships" on public.member_group_members
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

drop policy if exists "Members read memberships of their groups" on public.member_group_members;
create policy "Members read memberships of their groups" on public.member_group_members
  for select using (
    profile_id = auth.uid()
    or public.is_group_participant(group_id, auth.uid())
    or public.is_site_admin(auth.uid())
  );

drop policy if exists "Members join groups themselves" on public.member_group_members;
create policy "Members join groups themselves" on public.member_group_members
  for insert with check (
    (
      profile_id = auth.uid()
      and exists (
        select 1 from public.profiles p
         where p.id = auth.uid() and p.membership_status = 'approved'
      )
      and exists (
        select 1 from public.member_groups g
         where g.id = group_id and g.is_archived = false and g.visibility <> 'private'
      )
    )
    or public.is_group_admin(group_id, auth.uid())
    or public.is_site_admin(auth.uid())
  );

drop policy if exists "Members and group admins update memberships" on public.member_group_members;
create policy "Members and group admins update memberships" on public.member_group_members
  for update using (
    profile_id = auth.uid()
    or public.is_group_admin(group_id, auth.uid())
    or public.is_site_admin(auth.uid())
  ) with check (
    profile_id = auth.uid()
    or public.is_group_admin(group_id, auth.uid())
    or public.is_site_admin(auth.uid())
  );

drop policy if exists "Members leave and admins remove" on public.member_group_members;
create policy "Members leave and admins remove" on public.member_group_members
  for delete using (
    profile_id = auth.uid()
    or public.is_group_admin(group_id, auth.uid())
    or public.is_site_admin(auth.uid())
  );

-- member_group_messages -----------------------------------------------------

drop policy if exists "Service role manages group messages" on public.member_group_messages;
create policy "Service role manages group messages" on public.member_group_messages
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

drop policy if exists "Group participants read messages" on public.member_group_messages;
create policy "Group participants read messages" on public.member_group_messages
  for select using (
    public.is_group_participant(group_id, auth.uid())
    or public.is_site_admin(auth.uid())
  );

drop policy if exists "Active members post messages" on public.member_group_messages;
create policy "Active members post messages" on public.member_group_messages
  for insert with check (
    profile_id = auth.uid()
    and public.is_active_group_member(group_id, auth.uid())
    and exists (
      select 1 from public.member_groups g
       where g.id = group_id and g.is_archived = false
    )
  );

-- Soft-delete only. There is deliberately no delete policy on this table.
drop policy if exists "Authors and moderators soft-delete messages" on public.member_group_messages;
create policy "Authors and moderators soft-delete messages" on public.member_group_messages
  for update using (
    profile_id = auth.uid()
    or public.is_group_admin(group_id, auth.uid())
    or public.is_site_admin(auth.uid())
  ) with check (
    profile_id = auth.uid()
    or public.is_group_admin(group_id, auth.uid())
    or public.is_site_admin(auth.uid())
  );

-- ---------------------------------------------------------------------------
-- Starter groups
-- ---------------------------------------------------------------------------

insert into public.member_groups (slug, name, description, topic, visibility)
values
  (
    'founders-and-builders',
    'Founders & Builders',
    'Awardees building companies, products and teams. Share what you are working on, ask for introductions, and compare notes on the hard parts.',
    'Entrepreneurship',
    'open'
  ),
  (
    'climate-and-sustainability',
    'Climate & Sustainability',
    'Climate action, clean energy, conservation and sustainable development work across the continent.',
    'Climate',
    'open'
  ),
  (
    'policy-and-advocacy',
    'Policy & Advocacy',
    'Public policy, governance, human rights and advocacy campaigns — the work of changing the rules.',
    'Policy',
    'open'
  )
on conflict (slug) do nothing;

comment on column public.member_groups.member_count is
  'Count of active memberships. Maintained by sync_member_group_member_count(); never set directly.';
comment on column public.member_group_members.last_read_at is
  'Last time this member opened the group. Messages newer than this are unread.';

------------------------------------------------------------------------
-- END supabase/migrations/20260728_member_groups.sql
------------------------------------------------------------------------

------------------------------------------------------------------------
-- BEGIN supabase/migrations/20260728_member_posts.sql
------------------------------------------------------------------------
-- Member-authored posts on the public awardee profile.
--
-- Deliberately NOT the editorial `posts` table: member posts need their own
-- ownership column, their own moderation lifecycle, and a different URL space
-- (/awardees/<awardee-slug>/posts/<post-slug>). Reusing `posts` would have
-- meant one table where "who may publish this" depends on a nullable column.
--
-- Prerequisite: supabase/SETUP-MEMBER-HUB.sql must already have been run
-- (public.profiles must exist).
create extension if not exists "pgcrypto";

create table if not exists public.member_posts (
  id uuid primary key default gen_random_uuid(),

  -- cascade, not restrict: a member post carries no payment or courier record,
  -- so there is nothing that has to outlive the profile that wrote it.
  profile_id uuid not null references public.profiles(id) on delete cascade,

  -- Unique per author, not globally: two awardees may each have a `my-story`
  -- post, because the public URL is already namespaced by the awardee slug.
  slug text not null,

  title text not null check (char_length(title) between 3 and 160),
  excerpt text check (char_length(excerpt) <= 320),
  -- Raw markdown. Stored verbatim and escaped at render time — never
  -- sanitised on write, so the original is always recoverable.
  body text not null check (char_length(body) between 20 and 40000),
  cover_url text,
  tags text[] not null default '{}',

  -- draft     : author-only, never public.
  -- published : visible on the public profile.
  -- flagged   : hidden from public by an admin; the author sees the note and
  --             may fix and re-publish.
  -- removed   : hidden permanently. The author may neither edit, re-publish
  --             nor delete it — the row is the moderation record.
  status text not null default 'draft'
    check (status in ('draft', 'published', 'flagged', 'removed')),

  moderation_note text,
  moderated_by uuid references public.profiles(id) on delete set null,

  published_at timestamptz,
  view_count integer not null default 0 check (view_count >= 0),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint member_posts_slug_per_author unique (profile_id, slug),

  -- A published post must have a publication timestamp: without this the
  -- public list could order by a NULL published_at and silently drop rows.
  constraint member_posts_published_needs_timestamp check (
    status <> 'published' or published_at is not null
  )
);

-- The dashboard list: every post by one author, any status.
create index if not exists member_posts_profile_status_idx
  on public.member_posts (profile_id, status);

-- The public feed and the admin moderation queue.
create index if not exists member_posts_status_published_idx
  on public.member_posts (status, published_at desc);

create or replace function public.touch_member_posts_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists member_posts_set_updated_at on public.member_posts;
create trigger member_posts_set_updated_at
  before update on public.member_posts
  for each row execute function public.touch_member_posts_updated_at();

alter table public.member_posts enable row level security;

-- Defence in depth. Every server route uses the service-role client and so
-- bypasses all of this; these policies exist for direct PostgREST access.

drop policy if exists "Anyone reads published member posts" on public.member_posts;
create policy "Anyone reads published member posts" on public.member_posts
  for select using (status = 'published');

drop policy if exists "Members read their own member posts" on public.member_posts;
create policy "Members read their own member posts" on public.member_posts
  for select using (auth.uid() = profile_id);

drop policy if exists "Members create their own member posts" on public.member_posts;
create policy "Members create their own member posts" on public.member_posts
  for insert with check (
    auth.uid() = profile_id
    and status in ('draft', 'published')
  );

-- A member may never move a post into (or out of) a moderation status. The API
-- enforces this too — RLS alone would not, since the API is the only place the
-- "was it already removed" rule can produce a useful error message.
drop policy if exists "Members update their own member posts" on public.member_posts;
create policy "Members update their own member posts" on public.member_posts
  for update
  using (auth.uid() = profile_id and status <> 'removed')
  with check (auth.uid() = profile_id and status in ('draft', 'published'));

drop policy if exists "Members delete their own member posts" on public.member_posts;
create policy "Members delete their own member posts" on public.member_posts
  for delete using (auth.uid() = profile_id and status <> 'removed');

drop policy if exists "Admins manage member posts" on public.member_posts;
create policy "Admins manage member posts" on public.member_posts
  for all
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role in ('admin', 'superadmin')
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role in ('admin', 'superadmin')
    )
  );

drop policy if exists "Service role manages member posts" on public.member_posts;
create policy "Service role manages member posts" on public.member_posts
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

comment on table public.member_posts is
  'Awardee-authored posts shown at /awardees/<slug>/posts/<post-slug>. Publish-immediately, moderate-after.';
comment on column public.member_posts.slug is
  'Unique per author only — the public URL is namespaced by the awardee slug.';
comment on column public.member_posts.body is
  'Raw markdown. Never sanitised on write; escaped at render time.';

------------------------------------------------------------------------
-- END supabase/migrations/20260728_member_posts.sql
------------------------------------------------------------------------

------------------------------------------------------------------------
-- BEGIN supabase/migrations/20260728_opportunities.sql
------------------------------------------------------------------------
-- Exclusive, member-only opportunities.
--
-- The existing /api/opportunities route is a public, unauthenticated proxy over
-- an external feed. This table is the admin-managed store that sits alongside
-- it and adds the thing awardees actually pay for: listings outsiders cannot
-- see. Visibility tiering is enforced server-side by visibleTiersFor() in
-- lib/opportunities/server.ts; the RLS policies below are defence in depth.
--
-- Prerequisite: supabase/SETUP-MEMBER-HUB.sql must already have been run
-- (public.profiles.membership_status is referenced by the 'approved' tier).
create extension if not exists "pgcrypto";

create table if not exists public.opportunities (
  id uuid primary key default gen_random_uuid(),

  title text not null check (char_length(title) between 3 and 200),
  slug text not null unique,
  -- Scholarship / Fellowship / Grant / Internship / Job / Mentorship / Programme
  type text not null,

  organization text,
  location text,
  summary text,
  description text, -- markdown
  application_url text,
  contact_email text,

  deadline date,
  amount_note text,

  -- 'public'   — anyone, including signed-out visitors
  -- 'members'  — any signed-in member
  -- 'approved' — only members whose profiles.membership_status = 'approved'
  visibility text not null default 'members'
    check (visibility in ('public', 'members', 'approved')),

  is_featured boolean not null default false,

  status text not null default 'draft'
    check (status in ('draft', 'published', 'closed', 'archived')),

  created_by uuid references public.profiles(id) on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists opportunities_status_deadline_idx
  on public.opportunities (status, deadline);

create index if not exists opportunities_visibility_status_idx
  on public.opportunities (visibility, status);

-- A member bookmarking a listing.
create table if not exists public.opportunity_saves (
  id uuid primary key default gen_random_uuid(),
  opportunity_id uuid not null references public.opportunities(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (opportunity_id, profile_id)
);

create index if not exists opportunity_saves_profile_idx
  on public.opportunity_saves (profile_id);

-- Mirrors public.touch_award_orders_updated_at() in 20260726_award_orders.sql.
create or replace function public.touch_opportunities_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists opportunities_set_updated_at on public.opportunities;
create trigger opportunities_set_updated_at
  before update on public.opportunities
  for each row execute function public.touch_opportunities_updated_at();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.opportunities enable row level security;
alter table public.opportunity_saves enable row level security;

-- Signed-out visitors: published + public only. This is the SQL twin of
-- visibleTiersFor(null) === ['public'].
drop policy if exists "Anon reads public opportunities" on public.opportunities;
create policy "Anon reads public opportunities" on public.opportunities
  for select to anon
  using (status = 'published' and visibility = 'public');

-- Signed-in members: published rows their tier allows. 'approved' rows require
-- an approved membership_status, matching visibleTiersFor({ status }).
--
-- profiles.membership_status is added by supabase/SETUP-MEMBER-HUB.sql, which
-- may not have been run on this database yet. Rather than fail the whole
-- migration on a missing column, fall back to a policy that grants only the
-- 'public'/'members' tiers — the least privileged reading, never the most.
drop policy if exists "Members read opportunities in their tier" on public.opportunities;
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'profiles' and column_name = 'membership_status'
  ) then
    execute $policy$
      create policy "Members read opportunities in their tier" on public.opportunities
        for select to authenticated
        using (
          status = 'published'
          and (
            visibility in ('public', 'members')
            or (
              visibility = 'approved'
              and exists (
                select 1 from public.profiles p
                where p.id = auth.uid() and p.membership_status = 'approved'
              )
            )
          )
        )
    $policy$;
  else
    raise notice 'public.profiles.membership_status is missing — creating the members-tier policy without the approved tier. Run supabase/SETUP-MEMBER-HUB.sql, then re-run this migration.';
    execute $policy$
      create policy "Members read opportunities in their tier" on public.opportunities
        for select to authenticated
        using (status = 'published' and visibility in ('public', 'members'))
    $policy$;
  end if;
end $$;

drop policy if exists "Admins manage opportunities" on public.opportunities;
create policy "Admins manage opportunities" on public.opportunities
  for all to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role in ('admin', 'superadmin')
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role in ('admin', 'superadmin')
    )
  );

drop policy if exists "Service role manages opportunities" on public.opportunities;
create policy "Service role manages opportunities" on public.opportunities
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- A member may only ever see, create or remove their own bookmarks.
drop policy if exists "Members read their own saves" on public.opportunity_saves;
create policy "Members read their own saves" on public.opportunity_saves
  for select to authenticated using (auth.uid() = profile_id);

drop policy if exists "Members create their own saves" on public.opportunity_saves;
create policy "Members create their own saves" on public.opportunity_saves
  for insert to authenticated with check (auth.uid() = profile_id);

drop policy if exists "Members delete their own saves" on public.opportunity_saves;
create policy "Members delete their own saves" on public.opportunity_saves
  for delete to authenticated using (auth.uid() = profile_id);

drop policy if exists "Service role manages opportunity saves" on public.opportunity_saves;
create policy "Service role manages opportunity saves" on public.opportunity_saves
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

comment on column public.opportunities.visibility is
  'public | members | approved — the tier a caller must reach to see this row. Enforced by visibleTiersFor() in lib/opportunities/server.ts.';

------------------------------------------------------------------------
-- END supabase/migrations/20260728_opportunities.sql
------------------------------------------------------------------------

------------------------------------------------------------------------
-- BEGIN supabase/migrations/20260729_index_foreign_keys.sql
------------------------------------------------------------------------
-- 20260729_index_foreign_keys.sql
-- unindexed_foreign_keys: every FK below had no covering index, so each parent
-- delete forced a sequential scan of the child table to enforce the constraint,
-- and joins across the FK could not use an index. Idempotent.
--
-- Driven off pg_constraint rather than a hard-coded list, because three of the
-- affected tables (notification_history, support_tickets, support_messages)
-- exist in the live project but have no CREATE TABLE anywhere in this repo, so
-- naming them directly would break a fresh SETUP-ALL run.

do $$
declare fk record;
begin
  for fk in
    select c.conrelid, c.conrelid::regclass::text as tbl, c.conname,
      (select string_agg(quote_ident(a.attname), ', ' order by k.ord)
       from unnest(c.conkey) with ordinality k(attnum, ord)
       join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k.attnum) as cols
    from pg_constraint c
    join pg_class rel on rel.oid = c.conrelid
    join pg_namespace n on n.oid = rel.relnamespace
    where c.contype = 'f'
      and n.nspname = 'public'
      and not exists (
        select 1 from pg_index i
        where i.indrelid = c.conrelid
          and (i.indkey::int2[])[0:array_length(c.conkey, 1) - 1] = c.conkey
      )
  loop
    execute format(
      'create index if not exists %I on %s (%s)',
      'idx_' || fk.conname, fk.tbl, fk.cols
    );
  end loop;
end $$;

------------------------------------------------------------------------
-- END supabase/migrations/20260729_index_foreign_keys.sql
------------------------------------------------------------------------

------------------------------------------------------------------------
-- BEGIN supabase/migrations/20260729_security_hardening.sql
------------------------------------------------------------------------
-- 20260729_security_hardening.sql
-- Remediates the Supabase database-linter security findings reported 2026-07-27.
-- Idempotent: safe to re-run.

-- ---------------------------------------------------------------------------
-- 1. function_search_path_mutable
--    Pin search_path on every public function that lacks it, so a caller cannot
--    shadow `public` with a schema of their own and hijack an unqualified name.
-- ---------------------------------------------------------------------------
do $$
declare fn record;
begin
  for fn in
    select p.oid::regprocedure as sig
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proconfig is null
  loop
    execute format('alter function %s set search_path = public', fn.sig);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 2. anon/authenticated_security_definer_function_executable
--    Trigger functions are granted EXECUTE to anon/authenticated by Supabase's
--    default grants, which publishes them at /rest/v1/rpc/<name>. They are only
--    ever meant to fire from triggers, so take the grant away.
--
--    NOTE: the RLS helper functions (is_site_admin, is_group_participant,
--    is_active_group_member, is_group_admin) deliberately keep their grants.
--    Postgres checks EXECUTE privilege when evaluating an RLS policy expression
--    as the querying role, so revoking them would turn every member_groups read
--    into "permission denied" instead of an empty result. They are SECURITY
--    DEFINER by necessity (to break RLS recursion) and now have a pinned
--    search_path; they return only a boolean.
-- ---------------------------------------------------------------------------
do $$
declare fn record;
begin
  for fn in
    select p.oid::regprocedure as sig
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.prorettype = 'trigger'::regtype
  loop
    execute format('revoke all on function %s from anon, authenticated', fn.sig);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 3. security_definer_view — public.awardee_directory
--    The view stays SECURITY DEFINER on purpose: it is the curated public
--    projection of awardees ⋈ profiles, and `profiles` intentionally has no
--    anon SELECT policy. What is fixed here is the payload — the view no longer
--    selects email, personal_email or phone, so the definer bypass cannot leak
--    contact details. lib/awardees.ts already hard-codes those three to null and
--    app/api/awardees/[id]/route.ts strips email, so no consumer loses data.
-- ---------------------------------------------------------------------------
--    CREATE OR REPLACE VIEW cannot remove columns, so this is a drop/recreate.
drop view if exists public.awardee_directory;

create view public.awardee_directory as
  select
    a.id as awardee_id,
    coalesce(p.id, a.profile_id) as profile_id,
    coalesce(p.slug, a.slug) as slug,
    coalesce(p.full_name, a.name) as name,
    coalesce(p.location, a.country) as country,
    p.location,
    coalesce(p.current_school, a.course) as current_school,
    coalesce(p.field_of_study, a.course) as field_of_study,
    coalesce(p.bio, a.bio) as bio,
    coalesce(p.avatar_url, a.avatar_url, a.image_url) as avatar_url,
    p.cover_image_url,
    coalesce(p.headline, a.headline) as headline,
    coalesce(p.tagline, a.tagline) as tagline,
    coalesce(p.achievements, a.achievements) as achievements,
    coalesce(p.gallery, a.gallery) as gallery,
    coalesce(p.video_links, a.video_links) as video_links,
    coalesce(p.social_links, a.social_links) as social_links,
    coalesce(p.interests, a.interests) as interests,
    p.cohort,
    p.metadata,
    coalesce(p.cgpa, a.cgpa) as cgpa,
    coalesce(p.year, a.year) as year,
    a.featured,
    a.created_at,
    coalesce(p.updated_at, a.updated_at) as updated_at,
    coalesce(p.is_public, a.is_public, true) as is_public,
    coalesce(p.role, 'user'::text) as role,
    coalesce(p.mentor, ''::text) as mentor,
    coalesce(p.impact_projects, a.impact_projects, 0) as impact_projects,
    coalesce(p.lives_impacted, a.lives_impacted, 0) as lives_impacted,
    coalesce(p.awards_received, a.awards_received, 0) as awards_received,
    coalesce(p.youtube_video_url, a.youtube_video_url) as youtube_video_url
  from public.awardees a
  left join public.profiles p on p.id = a.profile_id
  where coalesce(p.is_public, a.is_public, true);

grant select on public.awardee_directory to anon, authenticated;

comment on view public.awardee_directory is
  'Public awardee projection. SECURITY DEFINER by design so anon can read it without a profiles SELECT policy; contains no contact PII.';

-- ---------------------------------------------------------------------------
-- 4. public.awardees leaked every awardee email to anon
--    RLS is row-level only, so the "is_public = true" policy still exposed the
--    email column to GET /rest/v1/awardees?select=email. Column-level grants
--    close that. service_role is unaffected, and every route that legitimately
--    reads awardee emails (search, verify-email, export, signup) uses
--    createAdminClient().
-- ---------------------------------------------------------------------------
do $$
declare col record;
begin
  revoke select on public.awardees from anon, authenticated;
  for col in
    select column_name
    from information_schema.columns
    where table_schema = 'public' and table_name = 'awardees'
      and column_name <> 'email'
  loop
    execute format('grant select (%I) on public.awardees to anon, authenticated', col.column_name);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 5. rls_policy_always_true
--    Every write to these three tables goes through createAdminClient(), which
--    uses service_role and bypasses RLS. The permissive anon policies are pure
--    attack surface: anyone with the publishable key could forge contact-form
--    messages or delete other people's push subscriptions.
-- ---------------------------------------------------------------------------
--    Guarded on to_regclass: push_subscriptions and magazine_downloads exist in
--    the live project but have no CREATE TABLE in this repo, so a fresh
--    SETUP-ALL run would otherwise fail here.
do $$
declare t record;
begin
  for t in
    select * from (values
      ('push_subscriptions', 'Anyone can create subscription'),
      ('push_subscriptions', 'Anyone can delete own subscription'),
      ('messages',           'Anyone can submit messages'),
      ('magazine_downloads', 'Allow public inserts')
    ) as v(tbl, pol)
  loop
    if to_regclass('public.' || t.tbl) is not null then
      execute format('drop policy if exists %I on public.%I', t.pol, t.tbl);
    end if;
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 6. public_bucket_allows_listing
--    `awardees` and `uploads` are public buckets, so objects are served over
--    /storage/v1/object/public/... without touching RLS. These SELECT policies
--    only enable /storage/v1/object/list/..., i.e. anonymous enumeration of
--    every file. Nothing in the app calls .list(); images keep working.
-- ---------------------------------------------------------------------------
drop policy if exists "Public Access"           on storage.objects;
drop policy if exists "Allow public read access" on storage.objects;

-- ---------------------------------------------------------------------------
-- 7. multiple_permissive_policies on public.awardees
--    Two exact-duplicate pairs, left over from an earlier migration.
-- ---------------------------------------------------------------------------
drop policy if exists "Public visible awardees"    on public.awardees;
drop policy if exists "Service manages all awardees" on public.awardees;

------------------------------------------------------------------------
-- END supabase/migrations/20260729_security_hardening.sql
------------------------------------------------------------------------

------------------------------------------------------------------------
-- BEGIN supabase/migrations/20260729_security_hardening_2.sql
------------------------------------------------------------------------
-- 20260729_security_hardening_2.sql
-- Second remediation pass: PUBLIC function grants, a broken posts UPDATE policy,
-- leftover duplicate policies, and the auth_rls_initplan performance lint.
-- Idempotent: safe to re-run.

-- ---------------------------------------------------------------------------
-- 1. The first pass revoked EXECUTE from anon/authenticated, but Postgres also
--    grants EXECUTE to PUBLIC by default (`=X/postgres` in proacl), which is
--    what actually kept every function reachable at /rest/v1/rpc/<name>.
--    Revoke from PUBLIC, then grant back only the RLS helpers that policies
--    genuinely need — policy expressions are evaluated with the querying role's
--    privileges, so without these grants member_groups reads would fail with
--    "permission denied" instead of returning an empty set.
--    No application code calls supabase.rpc() against this schema.
-- ---------------------------------------------------------------------------
revoke execute on all functions in schema public from public;

do $$
declare f record;
begin
  for f in
    select * from (values
      ('public.is_site_admin(uuid)',                'anon, authenticated'),
      ('public.is_group_participant(uuid, uuid)',   'anon, authenticated'),
      ('public.is_active_group_member(uuid, uuid)', 'anon, authenticated'),
      ('public.is_group_admin(uuid, uuid)',         'anon, authenticated'),
      ('public.is_post_owner(uuid)',                'authenticated')
    ) as v(sig, roles)
  loop
    if to_regprocedure(f.sig) is not null then
      execute format('grant execute on function %s to %s', f.sig, f.roles);
    end if;
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 2. posts_update_owner was created with USING (true) WITH CHECK (true) while
--    its three sibling policies all use is_post_owner(author_id). Any signed-in
--    user could edit or reassign any post. Restore the owner check.
-- ---------------------------------------------------------------------------
--    `posts` exists in the live project but has no CREATE TABLE in this repo,
--    so this is guarded for a fresh SETUP-ALL run.
do $$
begin
  if to_regclass('public.posts') is not null and to_regprocedure('public.is_post_owner(uuid)') is not null then
    drop policy if exists posts_update_owner on public.posts;
    create policy posts_update_owner on public.posts
      for update to authenticated
      using (is_post_owner(author_id))
      with check (is_post_owner(author_id));

    -- exact-duplicate permissive policies on the same table
    drop policy if exists "Public published posts"         on public.posts;
    drop policy if exists "Service role manages all posts"  on public.posts;
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 3. feature_requests accepted unauthenticated inserts. Every read and write in
--    app/api/feature-requests/route.ts uses createAdminClient(), so the anon
--    policy is unused attack surface.
-- ---------------------------------------------------------------------------
drop policy if exists "Anyone can submit feature_requests" on public.feature_requests;

-- ---------------------------------------------------------------------------
-- 4. awardees is read-only for anon/authenticated; all writes use service_role.
--    RLS already blocked these, but the grants had no reason to exist.
-- ---------------------------------------------------------------------------
revoke insert, update, delete, references on public.awardees from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5. auth_rls_initplan — wrap auth.uid() / auth.role() / auth.jwt() in a scalar
--    subquery so the planner evaluates them once per statement instead of once
--    per row. Rewrites each affected policy in place, preserving name, command,
--    roles and permissive/restrictive kind.
-- ---------------------------------------------------------------------------
do $$
declare
  p record;
  new_qual text;
  new_check text;
  cmd text;
  ddl text;
begin
  for p in
    select c.relname as tbl, pol.polname, pol.polcmd, pol.polpermissive,
      coalesce(
        (select string_agg(quote_ident(r.rolname), ', ') from pg_roles r where r.oid = any(pol.polroles)),
        'public') as roles,
      pg_get_expr(pol.polqual, pol.polrelid) as qual,
      pg_get_expr(pol.polwithcheck, pol.polrelid) as wc
    from pg_policy pol
    join pg_class c on c.oid = pol.polrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
  loop
    new_qual  := regexp_replace(p.qual, '(?<!SELECT )auth\.(uid|role|jwt)\(\)', '(select auth.\1())', 'g');
    new_check := regexp_replace(p.wc,   '(?<!SELECT )auth\.(uid|role|jwt)\(\)', '(select auth.\1())', 'g');

    continue when new_qual is not distinct from p.qual
             and new_check is not distinct from p.wc;

    cmd := case p.polcmd
             when 'r' then 'select' when 'a' then 'insert'
             when 'w' then 'update' when 'd' then 'delete'
             else 'all' end;

    ddl := format('create policy %I on public.%I as %s for %s to %s',
                  p.polname, p.tbl,
                  case when p.polpermissive then 'permissive' else 'restrictive' end,
                  cmd, p.roles);

    if new_qual is not null then
      ddl := ddl || format(' using (%s)', new_qual);
    end if;
    if new_check is not null then
      ddl := ddl || format(' with check (%s)', new_check);
    end if;

    execute format('drop policy %I on public.%I', p.polname, p.tbl);
    execute ddl;
  end loop;
end $$;

------------------------------------------------------------------------
-- END supabase/migrations/20260729_security_hardening_2.sql
------------------------------------------------------------------------
