// Shared gallery images data used across homepage and summit page
export const galleryImages = [
    {
        id: 1,
        thumb: "/thumbs/IMG_0672.jpg",
        src: "/IMG_0672.jpg",
        alt: "Awardees networking backstage",
        category: "Backstage",
        caption: "Awardees connecting backstage",
        credit: "Photo by Jane Smith",
    },
    {
        id: 2,
        thumb: "/thumbs/IMG_0673.jpg",
        src: "/IMG_0673.jpg",
        alt: "Community celebration",
        category: "Community",
        caption: "Local community celebrating with awardees",
        credit: "Photo by Mike Johnson",
    },
    {
        id: 3,
        thumb: "/thumbs/IMG_0674.jpg",
        src: "/IMG_0674.jpg",
        alt: "Media interviews",
        category: "Media",
        caption: "Press interviews with top awardees",
        credit: "Photo by Sarah Wilson",
    },
    {
        id: 4,
        thumb: "/thumbs/IMG_0675.jpg",
        src: "/IMG_0675.jpg",
        alt: "Award presentation moment",
        category: "Ceremony",
        caption: "Moment of award presentation",
        credit: "Photo by David Brown",
    },
    {
        id: 5,
        thumb: "/thumbs/IMG_0676.jpg",
        src: "/IMG_0676.jpg",
        alt: "Behind the scenes preparation",
        category: "Backstage",
        caption: "Final preparations before the ceremony",
        credit: "Photo by Lisa Davis",
    },
    {
        id: 6,
        thumb: "/thumbs/IMG_0677.jpg",
        src: "/IMG_0677.jpg",
        alt: "Community impact showcase",
        category: "Community",
        caption: "Showcasing community impact projects",
        credit: "Photo by Tom Anderson",
    },
    {
        id: 7,
        thumb: "/thumbs/IMG_0678.jpg",
        src: "/IMG_0678.jpg",
        alt: "Live broadcast setup",
        category: "Media",
        caption: "Live broadcast setup and coverage",
        credit: "Photo by Emma Taylor",
    },
    {
        id: 8,
        thumb: "/thumbs/IMG_0679.jpg",
        src: "/IMG_0679.jpg",
        alt: "Group photo of all awardees",
        category: "Ceremony",
        caption: "Group photo of all 100 awardees",
        credit: "Photo by Alex Chen",
    },
    {
        id: 9,
        thumb: "/thumbs/IMG_0680.jpg",
        src: "/IMG_0680.jpg",
        alt: "Mentorship session",
        category: "Backstage",
        caption: "Mentorship session with industry leaders",
        credit: "Photo by Maria Garcia",
    },
    {
        id: 10,
        thumb: "/thumbs/IMG_0681.jpg",
        src: "/IMG_0681.jpg",
        alt: "Local youth engagement",
        category: "Community",
        caption: "Engaging with local youth leaders",
        credit: "Photo by James Wilson",
    },
    {
        id: 11,
        thumb: "/thumbs/IMG_0682.jpg",
        src: "/IMG_0682.jpg",
        alt: "Documentary filming",
        category: "Media",
        caption: "Documentary crew capturing stories",
        credit: "Photo by Rachel Green",
    },
    {
        id: 12,
        thumb: "/thumbs/IMG_0683.jpg",
        src: "/IMG_0683.jpg",
        alt: "Leadership workshop",
        category: "Ceremony",
        caption: "Interactive leadership workshop",
        credit: "Photo by Michael Brown",
    },
    {
        id: 13,
        thumb: "/thumbs/IMG_0684.jpg",
        src: "/IMG_0684.jpg",
        alt: "Networking session",
        category: "Backstage",
        caption: "Awardees networking at the event",
        credit: "Photo by Sarah Lee",
    },
    {
        id: 14,
        thumb: "/thumbs/IMG_0685.jpg",
        src: "/IMG_0685.jpg",
        alt: "Community engagement",
        category: "Community",
        caption: "Community members engaging with leaders",
        credit: "Photo by David Kim",
    },
]

export type GalleryImage = typeof galleryImages[number]
